project:
  type: website
  output-dir: docs

website:
  favicon: logo.jpg
  title: "Research and Data Incubator"
  back-to-top-navigation: true
  page-navigation: true
  sidebar:
    style: "docked"
    logo: logo.jpg
    contents:
      - section: "Home"
        contents:
          - index.qmd
          - strength.qmd
          - business.qmd
      - customers.qmd
      - contact.qmd
  search:
    location: sidebar
    type: overlay
  
          

format:
  html:
    theme: journal
    css: styles.css
    toc: True
    toc-depth: 4
    toc-expand: true
    number-sections: true
    highlight-style: tango